Story1
AlinaNeculai/collector_pokemon pull request #3
Opened 2021-06-02 12:59 UTC by AlinaNeculai

2021-06-02 13:17 UTC, mporam requested changes

2021-06-02 13:17 UTC, mporam commented on functions.php
> +    $pokemon = $query->fetchALL();
should have lowercase `ll` in `fetchAll`

2021-06-02 13:17 UTC, mporam commented on functions.php
> +        $output .= '<div class="description">'. '<div class="pokemon-name">'. '<p class="pokemon-heading">'.
you dont need to concatenate every html element, only the PHP variables:
```
$output .= '<div class="description"><div class="pokemon-name"><p class="pokemon-heading">' . $pokemon['name'] . '</p></div>'.
```

2021-06-02 13:17 UTC, mporam commented on pokemons_2021-06-01.sql
> +  `type` mediumtext,
this could be an int as it only contains a number now

2021-06-02 13:17 UTC, mporam commented on pokemons_2021-06-01.sql
> +# ************************************************************
this looks like an old export, where is the types table?

2021-06-02 13:17 UTC, mporam commented on test/functions.php
> +        $result = DisplayPokemon($input);
the function has a lowercase `d`

2021-06-02 13:17 UTC, mporam commented on test/functions.php
> +        DisplayPokemon($input);
again, lowercase `d`

2021-06-02 13:17 UTC, mporam commented on test/functions.php
> +        $expected = '<section class="pokedex"></section>';
is this what you want your code to do? would it not be better if the function returned a message saying "no pokemon present" or something?

2021-06-02 14:51 UTC, nealioa requested changes

2021-06-02 14:51 UTC, nealioa commented on functions.php
> +        $output .= '</section>';
This is indented too far. Should look like:
```
    foreach ... {
        ...
    }
    $output .= '</section>';
    return $output;
```

2021-06-02 14:51 UTC, nealioa commented on index.php
> +    <link rel="stylesheet" href="resources/css/normalize.css">
Put normalize.css before your main.css. This way it won't override any styles you have created.

2021-06-02 14:51 UTC, nealioa commented on test/functions.php
> +
Unnecessary blank line.

2021-06-02 16:09 UTC, nealioa requested changes
A couple of blank lines you could get rid of.

And did you see Mike's comment in testDisplayPokemonFailure() about what displayPokemon() could return if it is given an empty array? It's worth thinking about. (We can chat tomorrow morning if you want.)

2021-06-02 16:09 UTC, nealioa commented on index.php
> +
Unnecessary blank line.

2021-06-02 16:09 UTC, nealioa commented on index.php
> +
Unnecessary blank line.

2021-06-03 09:48 UTC, nealioa requested changes

2021-06-03 09:48 UTC, nealioa commented on test/functions.php
> +                'type'=>'grass',
In `displayPokemon()` the key is `pokemon_type`.

2021-06-03 09:48 UTC, nealioa commented on test/functions.php
> +                    '<p class="type">Type: </p></div><div class="type-class"><p class="height">Height: 2</p>' .
I thought the word grass would be included here.

2021-06-03 10:09 UTC, nealioa approved these changes

2021-06-03 10:14 UTC, merged